services:
  goalbot:
    container_name: goalbot
    image: ghcr.io/francisjgarcia/goalbot:local
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.local
    env_file:
      - .env
      - ../src/.env
    volumes:
      - ../src:/app
      - ../tests:/app/tests
    user: root
    tty: true
    command: /bin/sh
    restart: on-failure
